// Nguyễn Tấn Hải 2021-11-11

// Tour
export const tableColumnsTour = [
  {
    field: `tourId`,
    headerName: "Mã tour",
    sortTable: true,
    unSortIcon: true,
    filter: true,
    headerSelect: true,
    checkboxSelection: true,
    headerCheckboxSelectionFilteredOnly: true,
    headerCheckboxSelection: true,
    minWidth: 170,
    with: 170,
  },
  {
    field: "tourName",
    headerName: "Tên tour",
    filter: true,
    minWidth: 300,
  },
  {
    field: "description",
    headerName: "Mô tả tour",
    minWidth: 200,
  },
  {
    field: "tourImg",
    headerName: "Ảnh tour",
    minWidth: 190,
  },
  {
    field: "phuongTienXuatPhat",
    headerName: "Phương tiện xuất phát",
    filter: true,
    minWidth: 220,
  },
  {
    field: "provinceName",
    headerName: "Địa điểm xuất phát",
    minWidth: 200,
  },
  {
    field: "dateStart",
    headerName: "Ngày bắt đầu",
    minWidth: 130,
  },
  {
    field: "dateEnd",
    headerName: "Ngày kết thúc",
    minWidth: 130,
  },
  {
    field: "quanityMax",
    headerName: "SL Max",
    sortTable: true,
    unSortIcon: true,
    filter: "agNumberColumnFilter",
    minWidth: 120,
  },
  {
    field: "quanityMin",
    headerName: "SL Min",
    sortTable: true,
    unSortIcon: true,
    filter: "agNumberColumnFilter",
    minWidth: 120,
  },
  {
    field: "currentQuanity",
    headerName: "SL hiện tại",
    sortTable: true,
    unSortIcon: true,
    filter: "agNumberColumnFilter",
    minWidth: 150,
  },
];
export const tableColumnEmployee = [
  {
    field: `empId`,
    headerName: "Mã nhân viên",
    sortTable: true,
    unSortIcon: true,
    filter: false,
    headerSelect: true,
    checkboxSelection: true,
    headerCheckboxSelection: true,
    minWidth: 200,
  },
  {
    field: `empName`,
    headerName: "Tên nhân viên",
    sortTable: true,
    unSortIcon: true,
    filter: false,
    headerSelect: true,
    checkboxSelection: false,
    headerCheckboxSelection: false,
    minWidth: 250,
  },
  {
    field: `gender`,
    headerName: "Giới tính",
    sortTable: false,
    unSortIcon: false,
    filter: false,
    headerSelect: true,
    checkboxSelection: false,
    headerCheckboxSelection: false,
    minWidth: 170,
  },
  {
    field: `dateOfBirth`,
    headerName: "Ngày sinh",
    sortTable: false,
    unSortIcon: false,
    filter: false,
    headerSelect: true,
    checkboxSelection: false,
    headerCheckboxSelection: false,
    minWidth: 170,
  },
  {
    field: `workingDate`,
    headerName: "Ngày vào làm",
    sortTable: false,
    unSortIcon: false,
    filter: false,
    headerSelect: true,
    checkboxSelection: false,
    headerCheckboxSelection: false,
    minWidth: 170,
  },
  {
    field: `phoneNumber`,
    headerName: "Số điện thoại",
    sortTable: false,
    unSortIcon: false,
    filter: false,
    headerSelect: true,
    checkboxSelection: false,
    headerCheckboxSelection: false,
    minWidth: 170,
  },
  {
    field: `email`,
    headerName: "Email",
    sortTable: false,
    unSortIcon: false,
    filter: false,
    headerSelect: true,
    checkboxSelection: false,
    headerCheckboxSelection: false,
    minWidth: 200,
  },
  {
    field: `dateUpdate`,
    headerName: "Ngày cập nhật",
    sortTable: false,
    unSortIcon: false,
    filter: false,
    headerSelect: true,
    checkboxSelection: false,
    headerCheckboxSelection: false,
    minWidth: 200,
  },
];

export const tableColumnTouristAttr = [
  {
    field: `touristAttrId`,
    headerName: "Mã địa điểm",
    sortTable: true,
    unSortIcon: true,
    filter: true,
    headerSelect: true,
    checkboxSelection: true,
    headerCheckboxSelection: true,
    minWidth: 170,
  },
  {
    field: `touristAttrName`,
    headerName: "Tên địa điểm",
    sortTable: false,
    unSortIcon: false,
    filter: false,
    headerSelect: false,
    checkboxSelection: false,
    headerCheckboxSelection: false,
    minWidth: 200,
  },
  {
    field: `description`,
    headerName: "Chi tiết",
    sortTable: false,
    unSortIcon: false,
    filter: false,
    headerSelect: false,
    checkboxSelection: false,
    headerCheckboxSelection: false,
    minWidth: 500,
  },
  {
    field: `dateUpdate`,
    headerName: "Ngày cập nhật",
    sortTable: false,
    unSortIcon: false,
    filter: false,
    headerSelect: false,
    checkboxSelection: false,
    headerCheckboxSelection: false,
    minWidth: 170,
  },
  {
    field: `provinceName`,
    headerName: "Tỉnh thành",
    sortTable: false,
    unSortIcon: false,
    filter: false,
    headerSelect: false,
    checkboxSelection: false,
    headerCheckboxSelection: false,
    minWidth: 200,
  },
  {
    field: `empName`,
    headerName: "Nhân viên",
    sortTable: false,
    unSortIcon: false,
    filter: false,
    headerSelect: false,
    checkboxSelection: false,
    headerCheckboxSelection: false,
    minWidth: 200,
  },
];

//tinhr thanh
export const tableColumnProvince = [
  {
    field: `provinceId`,
    headerName: "Mã tỉnh/ thành",
    sortTable: true,
    unSortIcon: true,
    filter: false,
    headerSelect: true,
    checkboxSelection: false,
    headerCheckboxSelection: false,
    minWidth: 200,
  },
  {
    field: `divisionType`,
    headerName: "Loại tỉnh/ thành",
    sortTable: false,
    unSortIcon: false,
    filter: false,
    headerSelect: false,
    checkboxSelection: false,
    headerCheckboxSelection: false,
    minWidth: 290,
  },
  {
    field: `provinceName`,
    headerName: "Tên tỉnh/ thành",
    sortTable: false,
    unSortIcon: false,
    filter: false,
    headerSelect: false,
    checkboxSelection: false,
    headerCheckboxSelection: false,
    minWidth: 290,
  },
  {
    field: `count`,
    headerName: "Số địa điểm du lịch",
    sortTable: false,
    unSortIcon: false,
    filter: false,
    headerSelect: false,
    checkboxSelection: false,
    headerCheckboxSelection: false,
    minWidth: 200,
  },
  {
    field: `regions`,
    headerName: "Miền",
    sortTable: false,
    unSortIcon: false,
    filter: false,
    headerSelect: false,
    checkboxSelection: false,
    headerCheckboxSelection: false,
    minWidth: 290,
  },
];

//quận huyện
export const tableColumnDistrict = [
  {
    field: `districtId`,
    headerName: "Mã quận/ huyện",
    sortTable: true,
    unSortIcon: true,
    filter: false,
    headerSelect: true,
    checkboxSelection: false,
    headerCheckboxSelection: false,
    minWidth: 200,
  },
  {
    field: `divisionType`,
    headerName: "Loại quận/ huyện",
    sortTable: false,
    unSortIcon: false,
    filter: false,
    headerSelect: false,
    checkboxSelection: false,
    headerCheckboxSelection: false,
    minWidth: 300,
  },
  {
    field: `districtName`,
    headerName: "Tên quận/ huyện",
    sortTable: false,
    unSortIcon: false,
    filter: false,
    headerSelect: false,
    checkboxSelection: false,
    headerCheckboxSelection: false,
    minWidth: 300,
  },
  {
    field: `provinceName`,
    headerName: "Tên tỉnh/ thành",
    sortTable: false,
    unSortIcon: false,
    filter: false,
    headerSelect: false,
    checkboxSelection: false,
    headerCheckboxSelection: false,
    minWidth: 300,
  },
  {
    field: `count`,
    headerName: "số lượng phường/ xã",
    sortTable: false,
    unSortIcon: false,
    filter: false,
    headerSelect: false,
    checkboxSelection: false,
    headerCheckboxSelection: false,
    minWidth: 200,
  },
];
//phường
export const tableColumnWard = [
  {
    field: `wardId`,
    headerName: "Mã phường/xã",
    sortTable: true,
    unSortIcon: true,
    filter: false,
    headerSelect: true,
    checkboxSelection: false,
    headerCheckboxSelection: false,
    minWidth: 290,
  },
  {
    field: `divisionType`,
    headerName: "Loại",
    sortTable: false,
    unSortIcon: false,
    filter: false,
    headerSelect: false,
    checkboxSelection: false,
    headerCheckboxSelection: false,
    minWidth: 290,
  },
  {
    field: `wardName`,
    headerName: "Tên phường/ xã",
    sortTable: false,
    unSortIcon: false,
    filter: false,
    headerSelect: false,
    checkboxSelection: false,
    headerCheckboxSelection: false,
    minWidth: 290,
  },
  {
    field: `districtName`,
    headerName: "Tên quận/ huyện",
    sortTable: false,
    unSortIcon: false,
    filter: false,
    headerSelect: false,
    checkboxSelection: false,
    headerCheckboxSelection: false,
    minWidth: 290,
  },
];

///export column tourGuide
export const tableColumnTourGuide = [
  {
    field: `tourGuideId`,
    headerName: "Mã nhân viên",
    sortTable: true,
    unSortIcon: true,
    filter: false,
    headerSelect: true,
    checkboxSelection: true,
    headerCheckboxSelection: true,
    minWidth: 200,
  },
  {
    field: `tourGuideName`,
    headerName: "Tên nhân viên",
    sortTable: true,
    unSortIcon: true,
    filter: false,
    headerSelect: true,
    checkboxSelection: false,
    headerCheckboxSelection: false,
    minWidth: 200,
  },
  {
    field: `gender`,
    headerName: "Giới tính",
    sortTable: false,
    unSortIcon: false,
    filter: false,
    headerSelect: true,
    checkboxSelection: false,
    headerCheckboxSelection: false,
    minWidth: 100,
  },
  {
    field: `dateOfBirth`,
    headerName: "Ngày sinh",
    sortTable: false,
    unSortIcon: false,
    filter: false,
    headerSelect: true,
    checkboxSelection: false,
    headerCheckboxSelection: false,
    minWidth: 170,
  },
  {
    field: `address`,
    headerName: "Địa chỉ",
    sortTable: false,
    unSortIcon: false,
    filter: false,
    headerSelect: true,
    checkboxSelection: false,
    headerCheckboxSelection: false,
    minWidth: 300,
  },
  {
    field: `phoneNumber`,
    headerName: "Số điện thoại",
    sortTable: false,
    unSortIcon: false,
    filter: false,
    headerSelect: true,
    checkboxSelection: false,
    headerCheckboxSelection: false,
    minWidth: 170,
  },
  {
    field: `email`,
    headerName: "Email",
    sortTable: false,
    unSortIcon: false,
    filter: false,
    headerSelect: true,
    checkboxSelection: false,
    headerCheckboxSelection: false,
    minWidth: 200,
  },
  {
    field: `dateUpdate`,
    headerName: "Ngày cập nhật",
    sortTable: false,
    unSortIcon: false,
    filter: false,
    headerSelect: true,
    checkboxSelection: false,
    headerCheckboxSelection: false,
    minWidth: 150,
  },
  {
    field: `empName`,
    headerName: "Nhân viên",
    sortTable: false,
    unSortIcon: false,
    filter: false,
    headerSelect: true,
    checkboxSelection: false,
    headerCheckboxSelection: false,
    minWidth: 200,
  },
];
